"use client";

import "./globals.css";
import { useState } from "react";
import Header from "@/components/Header";
import SideBar from "@/components/SideBar";

export default function RootLayout({ children }) {
  const [drawerOpen, setDrawerOpen] = useState(false);

  return (
    <html lang="en">
      <body className="bg-gray-100">
        <Header onToggleDrawer={() => setDrawerOpen(!drawerOpen)} />

        <div className="flex">
          {/* Drawer Sidebar */}
          <SideBar open={drawerOpen} onClose={() => setDrawerOpen(false)} />

          {/* Main Page Content */}
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}


// import "./globals.css";
// import Sidebar from "@/components/SideBar";

// export const metadata = {
//   title: "AI Edu System",
//   description: "JEE/NEET video search & summarizer",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className="bg-gray-100">
//         <div className="flex min-h-screen">
//           <Sidebar />
//           <main className="flex-1 p-6">
//             {children}
//           </main>
//         </div>
//       </body>
//     </html>
//   );
// }


// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Sidebar from "@/components/xyz";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }



// export const metadata = {
//   title: "AI Edu System",
//   description: "JEE/NEET video search & summarizer",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className="bg-gray-100">
//         <div className="flex min-h-screen">
//           <Sidebar />
//           <main className="flex-1 p-6">
//             {children}
//           </main>
//         </div>
//       </body>
//     </html>
//   );
// }


