"use client";

import "./globals.css";
import { useState } from "react";
import YouTubeHeader from "@/components/YouTubeHeader";
import YouTubeSidebar from "@/components/YouTubeSidebar";

export default function RootLayout({ children }) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");

  return (
    <html lang="en" className="dark">
      <body className="bg-white dark:bg-[#0f0f0f] text-gray-900 dark:text-white antialiased">
        <YouTubeHeader
          onToggleSidebar={() => setSidebarOpen(!sidebarOpen)}
          searchQuery={searchQuery}
          onSearchChange={setSearchQuery}
          onSearchSubmit={() => {
            if (searchQuery.trim()) {
              window.location.href = `/youtube?q=${encodeURIComponent(
                searchQuery
              )}`;
            }
          }}
        />

        <div className="flex">
          {/* Sidebar */}
          <YouTubeSidebar
            isOpen={sidebarOpen}
            onClose={() => setSidebarOpen(false)}
          />

          {/* Main Content */}
          <main
            className={`flex-1 transition-all duration-200 ${
              sidebarOpen ? "md:ml-64" : ""
            }`}
          >
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}

// import "./globals.css";
// import Sidebar from "@/components/SideBar";

// export const metadata = {
//   title: "AI Edu System",
//   description: "JEE/NEET video search & summarizer",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className="bg-gray-100">
//         <div className="flex min-h-screen">
//           <Sidebar />
//           <main className="flex-1 p-6">
//             {children}
//           </main>
//         </div>
//       </body>
//     </html>
//   );
// }

// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Sidebar from "@/components/xyz";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// export const metadata = {
//   title: "AI Edu System",
//   description: "JEE/NEET video search & summarizer",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className="bg-gray-100">
//         <div className="flex min-h-screen">
//           <Sidebar />
//           <main className="flex-1 p-6">
//             {children}
//           </main>
//         </div>
//       </body>
//     </html>
//   );
// }
